name: Build image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 8 1/7 * *'

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Build openresty
      run: docker run --rm -i debian:10 bash < build.sh
